[package]
name = "rtr"
version = "0.1.0"
edition = "2021"

[dependencies]
glow = "0.14.1"
glutin = "0.31.2"
glutin-winit = "0.4.2"
winit = { version = "0.29.10", features = ["rwh_05"] }
raw-window-handle = { version = "0.5" }